### ISSUE TITLE
Error at download_all_assets.sh

### ISSUE THREAD

**Issue by jonaycp** [KelianB/FaceNexus#2]
I found this line in download_all_assets.sh
(cd submodules/DSINE && mkdir -p ./projects/dsine/checkpoints/exp001_cvpr2024 && gdown 1Wyiei4a-lVM6izjTNoBLIC5-Rcy4jnaC -O ./submodules/DSINE/projects/dsine/checkpoints/exp001_cvpr2024/dsine.pt)

I guess is wrong because you first move to DSINE 
(cd submodules/DSINE) 
and then it´s a relative reference 
./submodules/DSINE/projects/dsine/checkpoints/exp001_cvpr2024/dsine.pt 
I guess the right one is 
./projects/dsine/checkpoints/exp001_cvpr2024/dsine.pt

**Comment by KelianB** [comment]
Thank you, this is now fixed (7ce6427).
